name = "SVBCR"
author = "nuclearcrackhead239"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "259cb04b7559864e512b14c479808cce8febe1a4bdb9818411b369c49b6db595"

[versions]
forge = "37.1.1"
minecraft = "1.17.1"
