name = "SVBCR"
author = "nuclearcrackhead239"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2f6707fa9a79515395517a189b5fefc08b15fd15e9bb8fbd07fad1188ff0b87"

[versions]
forge = "37.1.1"
minecraft = "1.17.1"
